[manifest]
version = "1.0.0"
dump_lua = true
priority = 50



[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''function Card:start_dissolve(dissolve_colours, silent, dissolve_time_fac, no_juice)'''
position = 'after'
payload = '''
    if SMODS.has_enhancement(self,'m_blah_lost') then SMODS.calculate_context({blah_lostTrigger = true,card=self}) return end
'''
match_indent = true


[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''function Card:remove()'''
position = 'after'
payload = '''
    if SMODS.has_enhancement(self,'m_blah_lost') and not G.STATES.GAME_OVER then
        SMODS.calculate_context({blah_lostTrigger = true,card=self})
        self.destroyed = false
        self.removed = false
        return
    end
'''
match_indent = true



[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''new_card:set_ability(other.config.center)'''
position = 'at'
payload = '''
    if not SMODS.has_enhancement(other,'m_blah_lost') then
        new_card:set_ability(other.config.center)
    else
        SMODS.calculate_context({blah_lostTrigger = true,card=other})
        SMODS.destroy_cards(new_card)
    end
'''
match_indent = true