[manifest]
version = "1.0.0"
dump_lua = true
priority = 50


[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''edition = poll_edition('wheel_of_fortune', nil, true, true)'''
position = 'after'
payload = '''
SMODS.calculate_context({wheel_used = true, edition = edition})
'''
match_indent = true
