#thanks to foo54 on discord for this, solved a ton of my problems

[manifest]
version = "1.0.0"
dump_lua = true
priority = 50

# Add info queue stuffs
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
   end'''
position = 'at'
payload = '''localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
   elseif _c.set == "blah_tooltips" then
         localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
     end
'''
match_indent = true