#this was supposed to be a function to destroy every white seal in the deck at the end of the round
#but im too stupid to implement (how to spell) that so its just nothing
#if you want to you can try to make it i would be eternally greatful
#the way i thought of was adding cards to a pool when applying the white seal and then
#iterating through the deck and destroying cards in that pool
#i couldnt find a good way to check if a card has a seal though or i wouldve used that

#ok update how tf do you destroy a table of cards

#update im #winning

[manifest]
version = "1.0.0"
priority = 0


#function comes from seals.lua
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''G.FUNCS.draw_from_discard_to_deck()'''
position = 'before'
payload = '''
BLAH.destroyWhiteSeals()
'''
match_indent = true