#this was supposed to be a function to destroy every white seal in the deck at the end of the round
#but im too stupid to implement (how to spell) that so its just nothing
#if you want to you can try to make it i would be eternally greatful
#the way i thought of was adding cards to a pool when applying the white seal and then
#iterating through the deck and destroying cards in that pool
#i couldnt find a good way to check if a card has a seal though or i wouldve used that

#ok update how tf do you destroy a table of cards

[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''
self.ability.seal = {}
'''
position = "before"
payload = '''
if self.seal == 'blah_white' then
    table.insert(BLAH.markedForDeath,Card)
end
'''

match_indent = true